title = '지하실'
description = '러스트로 배우는 시스템 프로그래밍'

lang = 'ko-kr'

[themeConfig]
lastUpdated = '마지막 수정'
smoothScroll = true

  [[themeConfig.nav]]
  text = '러스트'
  link = '/러스트/'

  [themeConfig.sidebar]
    [[themeConfig.sidebar."/러스트/"]]
      title = ''
      collapsable = false
      children = [ '/러스트/' ]

    [[themeConfig.sidebar."/러스트/"]]
      title = '기초'
      collapsable = false
      children = [
        '/러스트/시작하기/',
        '/러스트/기초-문법/'
      ]

    [[themeConfig.sidebar."/러스트/"]]
      title = '고급'
      collapsable = false
      children = [
        # '/러스트/시작하기/',
        # '/러스트/기초-문법/'
      ]

    [[themeConfig.sidebar."/러스트/"]]
      title = '부록'
      collapsable = false
      children = [
        '/러스트/용어-사전/',
      ]

  [[themeConfig.nav]]
  text = '시스템 프로그래밍'
  link = '/시스템-프로그래밍/'

  [[themeConfig.nav]]
  text = '아키텍처'
  link = '/아키텍처/'

  [[themeConfig.nav]]
  text = '운영체제'
  link = '/운영체제/'  

[plugins]
  [plugins.'@vuepress/google-analytics']
  ga = 'UA-130603275-1'
